### ISSUE TITLE
Trying this on Windows 10, sequential order not working.

### ISSUE THREAD

**Issue by Dorrie14** [mistic100/UMWP-Autochanger#11]
I am trying this program on Windows 10 and it is set for showing wallpapers in sequential order but it shows images in random rather than alphabetical order.

**Comment by mistic100** [comment]
Please confirm you set the read mode in the set properties and not only in the general **default** options.

OS should not interfer here and anyway I don't have W10

**Comment by Dorrie14** [comment]
Ah, did not realise I had to right-click on my folder to edit properties there too, have now set that to sequential too so problem should be sorted. Am a novice with this program, thanks for replying. :-))
