### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by rallymewrx** [mistic100/UMWP-Autochanger#12]
I have an issue where only one monitor will have an image. The other monitor 1 or 2 will be black. Sometimes pictures show up on both but only about 20% of the time I refresh. Some times both will have a black backgroud

**Comment by rallymewrx** [comment]
![image](https://cloud.githubusercontent.com/assets/13788773/9263052/9e824a70-41ce-11e5-8251-d952785faa85.png)

Its making an image that is half black or all black

**Comment by rallymewrx** [comment]
![image](https://cloud.githubusercontent.com/assets/13788773/9263072/c56bcb52-41ce-11e5-82d9-3dd926a4a180.png)

**Comment by mistic100** [comment]
Not sure at all the problem is W10.
If possible try the same config on W7.
I don't have W10 anyway.

**Comment by rallymewrx** [comment]
Also when i close the program and reopen it the set that I added is gone

**Comment by rallymewrx** [comment]
fixed it by using the zip download
the installer does not work on my system. even though it installs with no error message. I even tried using compatibility mode.

**Comment by LunyKimberly** [comment]
rallymewrx: Something that worked for me was giving it permanent Admin rights.

Go to the where the exe file is (program files (x86) umwp autochanger), right click the exe, Troubleshoot Compatibility, Troubleshoot program, tick "The program requires additional permissions", test program (add sets if need be), click next then "Yes, save these setting for this program", close button

Hope that helps others that have upgraded.

**Comment by mistic100** [comment]
Yeah l had to do that on every single software on the W10 computer at work, this is just insane, thank you Microsoft.

**Comment by mistic100** [comment]
I'll plan to move any user files (settings and cache) AppData.
The only problem I have with that is the portable version (ZIP) that should still store the data in it's own folder.
