### ISSUE TITLE
After upgrade 2.1 UMWP won't start

### ISSUE THREAD

**Issue by Infern1** [mistic100/UMWP-Autochanger#16]
Just updated to 2.1, then get this error:
![2016-01-21 08_21_23-new issue mistic100_umwp-autochanger](https://cloud.githubusercontent.com/assets/928787/12474045/0695d862-c018-11e5-87f8-9585b7092c18.png)

![2016-01-21 08_22_32-system](https://cloud.githubusercontent.com/assets/928787/12474062/22ca6052-c018-11e5-830a-1e4e829022c9.png)

**Comment by mistic100** [comment]
Perhaps I messed up the x86/x64 builds. I'll take a look this week end

**Comment by mistic100** [comment]
Please re-download the 2.1 installer http://www.strangeplanet.fr/work/umwp-autochanger
If everything is working as intended it will install the VC++ 2013 Redistribuable during installation.

**Comment by Infern1** [comment]
Problems still exist (tried to reinstall again today

**Comment by mistic100** [comment]
Sorry but I don't know what to do. I had it tested in a clean VM, and friends' computers without problem.
