### ISSUE TITLE
Folder per monitor

### ISSUE THREAD

**Issue by RyoSaeba2k6** [mistic100/UMWP-Autochanger#20]
Hello,

iv'e been using your WMWP Autochanger quite a while and i love it. But i have a question/wish to you.
Is it Possible to set up, that one specivic Monitor bekommst a selectet Folder of Wallpapers. I have an old 4:3 Monitor and two 16:9 Monitors. 
One of the 16:9 is running in Paviot (1080:1920)
1.Monitor 4:3 schould becomming only Wallpapers from the 4:3 Folder
2. Monitor 16:9 the normal 16:9 wallpapers
3. Monitor Paviot the Poster Wallpaper Folder.

by the way...
i have an bug with the new versions detection. The V2.1 says it is Version 2.0 and there is a newer Version. when i look in the help/about it says 2.0. At the changelog it says 2.1

thanks for this nice Program. if its not working its okay i love it anyway.

**Comment by mistic100** [comment]
If your only problem is the dimensions of your monitors you could use the same wallpapers in fill ![](https://raw.githubusercontent.com/mistic100/UMWP-Autochanger/master/src/images/icons/im_fill.png) mode. It will automatically crop the sides on the 4:3 monitor.

The version system is just not working, I know.

**Comment by RyoSaeba2k6** [comment]
i want that the Paviot monitor just shows  Poster images from the poster folder. fill mode looks bad if theres a 16:9 picture in in. Then the most of the Monitor is black.

**Comment by mistic100** [comment]
Ok I understood your message. Are you using an automatic translator ? "Paviot" is not a english word, you means pivot I guess, or portrait is better.

The fill mode won't display black borders, it's not the same as stretch proportionally ![](https://raw.githubusercontent.com/mistic100/UMWP-Autochanger/master/src/images/icons/im_stretch_prop.png).

Anyway I keep this idea somewhere but can't tell you of and when it will be done.

**Comment by RyoSaeba2k6** [comment]
no sorry, ive not used no translator.  I've thought this was the right word for it.
