### ISSUE TITLE
wallpaper history

### ISSUE THREAD

**Issue by whismerhill** [mistic100/UMWP-Autochanger#22]
What title says : 
an additional entry in the quick menu beside those : 
http://prntscr.com/ia4siz
for the functionality to ~~display the currently viewed wallpaper with your associated windows photo viewer~~

Alternatively : 
**"Show Wallpaper display history"/"Recent Wallpapers"** (shows the last 5 wallpapers displayed filenames including the current one + ability to click on them to open them )

reason : 
because sometimes I'm like : "hey I don't recall adding this pic, it's nice where it comes from ?"
ho it's "wallhaven-187398.jpg" => https://alpha.wallhaven.cc/wallpaper/187398

(wallpaper randomly chosen)

**Comment by mistic100** [comment]
Didn't found a better place. One day I'll develop a better view (custom system tray popin or whole GUI overhaul) but for now it will stay here.

**Comment by whismerhill** [comment]
ok
