### ISSUE TITLE
UMWP always changes windows setting to "Tile"

### ISSUE THREAD

**Issue by whismerhill** [mistic100/UMWP-Autochanger#26]
here's how UMWP is setup
http://prntscr.com/ibq5su
http://prntscr.com/ibq6t7
I'm on win 7 x64 if that matters.

The fact that "Tile" is chosen is sometimes causing unwelcome behavior when walls don't fit exactly.
if I change the windows setting to something else, then refresh UMWP then it's back to "Tile"

**Comment by mistic100** [comment]
What make thing it uses Tile mode ?
Didn't you forgot to configure the Custom mode ? (I guess you want 1 row and 3 columns in order to display the vertical wallpapers).

**Comment by whismerhill** [comment]
yeah that's exactly what I'm doing : 
http://prntscr.com/ibv7wj
sometimes there's a few left over pixels on the side ( just thinking out loud is this actually another issue ? no idea really, I didn't really make the calculations to see if the remaining space is because the wallpapers don't fill out my 1680 pixels wide..... )
so sometimes there's a few left over pixels on the side and the windows tile mode makes it therefore weird looking by repeating the wallpaper on the right side.

**Comment by mistic100** [comment]
Just make a screenshot, I don't understand a word of your description.

**Comment by whismerhill** [comment]
wasn't able to make a decent enough screenshot due to the random nature of the selected pictures it's not always very visible.
so I made a drawing : http://prntscr.com/ibzra2

**Comment by mistic100** [comment]
Ok.
I won't be able to help, there is no reason to get this behaviour as 1680 is perfectly divisible by 3.
As a workaround you can try adding a border. But can't do more.

**Comment by whismerhill** [comment]
why does it set windows to tile though ?

**Comment by mistic100** [comment]
It is the bast option to prevent Windows for doing unnecessary image treatments as the provided image is already at the perfect size.
This tool always worked like that.

It also necessary when working with multiple monitors when the main monitor is not the far-left one.

**Comment by whismerhill** [comment]
ha damnit!

**Comment by whismerhill** [comment]
found the problem : http://prntscr.com/ic03i1

**Comment by mistic100** [comment]
Please launch the exe with the "--log" parameter
```
"UWMP Autochanger.exe" --log
```

After closing it will create a debug.log file

**Comment by mistic100** [comment]
Ok I found the problem : http://doc.qt.io/qt-5/qrect.html#bottom
> Note that for historical reasons this function returns top() + height() - 1; use y() + height() to retrieve the true y-coordinate.

I don't exactly know why I don't have the problem

**Comment by whismerhill** [comment]
with --log 
the vertical set doesn't work anymore (black screen)
http://prntscr.com/ic080v
https://pastebin.com/jDyHmAyJ
horizontal set works just fine

and yeah good find & weird stuff _shrugs_

**Comment by mistic100** [comment]
I released 2.3.1. It should propose auto-update at startup.

**Comment by whismerhill** [comment]
Thanks a lot. issue fixed *bows*
