### ISSUE TITLE
desktop resolution & fullscreen games/apps & refresh

### ISSUE THREAD

**Issue by whismerhill** [mistic100/UMWP-Autochanger#27]
hi,
I found a small issue.
if you're a gamer and gaming at resolutions different from your desktop then UWMP might refresh while you're gaming and you'll end up with a wallpaper calculated for the wrong resolution.

**example:**
my desktop is set to 1680x1050
I recently played lethal league which sets my resolution to  3360x2100 and doesn't give me any other choice. Closing the game I ended up looking at a zoomed in wallpaper (because I believe it was calculated for 3360x2100 instead of 1680x1050)
I'm not sure if it does the same when lowering resolutions but I guess it should in theory.

it's not a huge issue by itself but still
so I thought maybe add an optional parameter that avoids refreshing the resolution calculation once UWMP has been started ? or something else there could be several approach to this one, that's IF you're interested to fix it, to begin with.
Either way, UWMP is great, it should be more popular

**Comment by mistic100** [comment]
the resolution should return to normal at the next refresh (the screen configuration is checked everytime before rendering the wallpaper)
