### ISSUE TITLE
cache size

### ISSUE THREAD

**Issue by whismerhill** [mistic100/UMWP-Autochanger#28]
hi, I just noticed that UWMP had a pretty large cache size of 3200 files totaling 1.2GB
located at C:\Users\USERNAME\AppData\Local\UMWP Autochanger\cache
I suppose this is related to this commit ? https://github.com/mistic100/UMWP-Autochanger/commit/3600d879d0b59ed8bd1e9f55f75bc10b6c31d269

in this case you can ignore or mark as fixed
otherwise would be awesome if you could look into it

**Comment by mistic100** [comment]
No, this commits clears temporary files, not the cache.

The cache contains cropped images to fit your monitors, in order to speed the next display of the same image and save some CPU cycles.

You can clear it manually from the "Configuration" menu.

**Comment by whismerhill** [comment]
there was actually several duplicates in there before I cleared it manually (yeah I didn't know about the clear cache option)

Otherwise basically the cache should stop to grow when it has cached every single file in the images folder ????
since my image folder is super large & I always add to it, that's a bit much to me but alright

**Comment by whismerhill** [comment]
actually maybe the duplicates date back to the old resolution issue I forgot to check before deleting

**Comment by mistic100** [comment]
I actually use UMWPA with a lot of images too, that's right the cache folder can grow a lot before being useful.

I'll make it configurable.

**Comment by mistic100** [comment]
On second thought I removed the cache
