### ISSUE TITLE
Double Click tray icon to change wallpaper

### ISSUE THREAD

**Issue by grinch843** [mistic100/UMWP-Autochanger#29]
Would like to have an option to set UMWP so that if you double click on the tray icon it will change the wallpaper instead of opening the app and use a right click option to open the app instead.

**Comment by mistic100** [comment]
You can set a global keyboard shortcut to change the wallpaper in the "hotkeys" tab. Is this enough ?

**Comment by grinch843** [comment]
Thats what I do now.  Used to use a wallpaper changer ALONG time ago that had that as an option and thought it would be a nice addition to this one :-)

**Comment by mistic100** [comment]
There is also right-click > Refresh on the tray icon.

I don't feel adding an option to add another trivial possibility.

**Comment by grinch843** [comment]
ok
