### ISSUE TITLE
Suggest wallpaper change corresponds to the clock

### ISSUE THREAD

**Issue by Airmis** [mistic100/UMWP-Autochanger#3]
Hello. Thanks for such a wonderful utilty and sorry for my poor english, i'm french...

Is it possible to have in a future release an option to change the wallpaper right on time, like does the windows7 wallpaper change ?

For example, when you set a 30 mn wallpaper change, the change occurs right at 17:00, then 17:30, and so on.

This is very usefull when you need to know when an hour is achieved.

Regards,
Airmis.

**Comment by mistic100** [comment]
won't fix, I can't think of a simple implementation + there are way better softwares like Rainmeter to have nice clock on desktop
