### ISSUE TITLE
Active files window shows only the top of file names

### ISSUE THREAD

**Issue by ianmit** [mistic100/UMWP-Autochanger#4]
The Active files window shows only the top of file names and is unusable. I have 30 inch 2560x1600 res monitors.
![active files pic](https://f.cloud.github.com/assets/6283976/2226231/fd6c86c4-9a9d-11e3-948d-e2edce4a3d33.jpg)
Cheers
Ian

**Comment by mistic100** [comment]
If you still use this software, version 2.0 should have fixed the problem.
